### ISSUE TITLE
Use JSON as datastore (activedata)

### ISSUE THREAD

**Issue by jonhue** [jonhue/jonhue#30]
Remove ...

```yaml
Metrics/BlockLength:
  Exclude:
    - db/seeds.rb
```

from `.rubocop.yml`
